### PR TITLE
Create navigation between screens

### PR DESCRIPTION
**Pull request by roobbs**
# Description

What did you implemented?:

- Added navigation on every touchable's part on all screens

### CODE REVIEW

**Review by YahirCl — APPROVED** [review]
Nice

**Review by RicardoRam781 — APPROVED** [review]
Good job!

**Review by ToshioRonin — APPROVED** [review]

**Review by Antonio3veces3 — COMMENTED** [review]
Well done!

**Review by cfcortesmx — APPROVED** [review]
Well done!

**Pull request merged**
